### ISSUE TITLE
Investigate improving startup time

### ISSUE THREAD

**Issue by WhoIsSethDaniel** [WhoIsSethDaniel/goldsmith.nvim#11]
Startup time is slow. The reason is obvious: a lot of checking for tools and retrieving information about them. This can and should be done asynchronously.

**Comment by seanrmurphy** [comment]
How slow are you thinking here? For me, using lunarvim, my startup time is almost 10s - if I disable `goldsmith` it drops to some hundreds of milliseconds.

It seem that this is due to some recent change (although it could of course be due to changes to my system config).

**Comment by WhoIsSethDaniel** [comment]
I don't see anything that bad. The worst startup time I've observed is just under 2s.  I ran `:GoInstallBinaries` and the startup time improved to just over 1s.  I'd be very interested to know what is causing a 10s (!) startup time.

**Comment by seanrmurphy** [comment]
So it seems to be something to do with the upgrade to go version 1.18 - when I downgrade to go 1.17, startup time is slightly over 1s, but upgrading again to  go 1.18 (1.18.3 specifically) it was taking over 8s.

I guess it's prob somehow an issue with my go configuration. Hmm....

**Comment by WhoIsSethDaniel** [comment]
Did you re-run `:GoInstallBinaries`? I am using 1.18.3 and my startup is slow, but nothing like 8s.

**Comment by WhoIsSethDaniel** [comment]
`:GoInstallBinaries` should print the error when an error occurs. I'll look into doing that.

**Comment by WhoIsSethDaniel** [comment]
Startup seems improved by recent PR #61
