### ISSUE TITLE
Remove "optional" requirement for nvim-lspinstall as it's no longer maintained

### ISSUE THREAD

**Issue by rgerardi** [WhoIsSethDaniel/goldsmith.nvim#2]
First of all, thank you for this plugin. It's great!

As a suggestions, you could remove the optional requirement for `nvim-lspinstall` as it's no longer maintained. The developer recommends using `nvim-lsp-installer` instead. By doing this, you eliminate a healhcheck warning that is confusing.

If you accept contributions I can submit a PR to do it.

**Comment by WhoIsSethDaniel** [comment]
This seems worthwhile. Please feel free to submit a PR. 

An unrelated question:  Where/how did you hear about Goldsmith?

**Comment by rgerardi** [comment]
I have submitted a PR to resolve this issue. Please review.

I have tested it with my current Neovim installation as well as a new installation and it looks good.

On the unrelated question: I've heard about Goldsmith in a tweet from Brian Ketelsen. I've been using both Neovim and this plugin only for a few days and really happy so far. Still comparing with my previous Vim + Vim-Go based setup.

**Comment by WhoIsSethDaniel** [comment]
I'd be interested in the conclusion(s) from your comparison.
