### ISSUE TITLE
nvim-lsp-installer deprecation warning / Lunarvim / nvim 0.7

### ISSUE THREAD

**Issue by solutionroute** [WhoIsSethDaniel/goldsmith.nvim#6]
Hi there - today I stumbled across both Lunarvim and thanks to [this tweet](https://twitter.com/bketelsen/status/1459504014538776577), Goldsmith, within a few minutes of one another.

It would appear some changes in Neovim since that tweet have occurred; despite the deprecation warning, all seems to perform as expected.

Running 0.7 release (not nightly) Neovim with current release of Lunarvim config; no local config or cache.

FYI, and thanks for Goldsmith.

```Error detected while processing /home/mw/.local/share/lunarvim/site/pack/packer/start/goldsmith.nvim/after/plugin/go.vim:
line   11:
E5108: Error executing lua ...art/nvim-lsp-installer/lua/nvim-lsp-installer/server.lua:74: Please set up servers directly via lspconfig instead of going through nvim-lsp-installer (this method is now deprecated)!
 Refer to :h nvim-lsp-installer-quickstart for more information.
stack traceback:
        [C]: in function 'assert'
        ...art/nvim-lsp-installer/lua/nvim-lsp-installer/server.lua:74: in function 'setup'
        ...acker/start/goldsmith.nvim/lua/goldsmith/lsp/servers.lua:35: in function 'run_setup_function'
        ...r/start/goldsmith.nvim/lua/goldsmith/autoconfig/init.lua:221: in function 'setup_server'
        ...r/start/goldsmith.nvim/lua/goldsmith/autoconfig/init.lua:184: in function 'init'
        [string "luaeval()"]:1: in main chunk
```

**Comment by WhoIsSethDaniel** [comment]
The latest main fixes this issue. There are a few other issues I am aware of.  For instance: if you are using a very recent nvim-lspconfig it will complain about the deprecation of client_capabilities. This should be fixed in an upcoming commit later this week.

**Comment by WhoIsSethDaniel** [comment]
I will leave this open. If you test and discover it works please close it.  Thank you.

**Comment by solutionroute** [comment]
Solved the lsp-installer deprecation warning; thanks! Time to dig into this further. Cheers
